# Generated by Django 3.2.4 on 2021-06-28 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filmweb', '0002_auto_20210628_1526'),
    ]

    operations = [
        migrations.AddField(
            model_name='film',
            name='imbq_rating',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=4),
        ),
        migrations.AddField(
            model_name='film',
            name='opis',
            field=models.TextField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='film',
            name='plakat',
            field=models.ImageField(blank=True, upload_to='plakaty'),
        ),
        migrations.AddField(
            model_name='film',
            name='premiera',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
