# Generated by Django 3.2.4 on 2021-07-16 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filmweb', '0005_auto_20210715_2133'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dodatkoweinfo',
            name='gatunek',
            field=models.PositiveSmallIntegerField(choices=[(3, 'Komedia'), (1, 'Horror'), (2, 'Sci-fi'), (4, 'Drama'), (0, 'Inne')], default=0),
        ),
        migrations.CreateModel(
            name='Aktor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imie', models.CharField(max_length=32)),
                ('nazwisko', models.CharField(max_length=32)),
                ('film', models.ManyToManyField(to='filmweb.Film')),
            ],
        ),
    ]
