# Generated by Django 3.2.4 on 2021-07-25 14:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('filmweb', '0006_auto_20210716_1306'),
    ]

    operations = [
        migrations.AddField(
            model_name='ocena',
            name='autor',
            field=models.ForeignKey(default='Anonim', on_delete=django.db.models.deletion.SET_DEFAULT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='dodatkoweinfo',
            name='gatunek',
            field=models.PositiveSmallIntegerField(choices=[(2, 'Sci-fi'), (4, 'Drama'), (1, 'Horror'), (0, 'Inne'), (3, 'Komedia')], default=0),
        ),
    ]
