# Generated by Django 3.2.4 on 2021-07-25 14:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('filmweb', '0010_auto_20210725_1628'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dodatkoweinfo',
            name='gatunek',
            field=models.PositiveSmallIntegerField(choices=[(3, 'Komedia'), (2, 'Sci-fi'), (1, 'Horror'), (0, 'Inne'), (4, 'Drama')], default=0),
        ),
        migrations.AlterField(
            model_name='ocena',
            name='autor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
