# Generated by Django 3.2.4 on 2021-07-25 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filmweb', '0015_auto_20210725_1640'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ocena',
            name='user',
        ),
        migrations.AddField(
            model_name='ocena',
            name='autor',
            field=models.CharField(default='Anonim', max_length=64),
        ),
        migrations.AlterField(
            model_name='dodatkoweinfo',
            name='gatunek',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Horror'), (0, 'Inne'), (2, 'Sci-fi'), (3, 'Komedia'), (4, 'Drama')], default=0),
        ),
    ]
