# Generated by Django 3.2.4 on 2021-07-25 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filmweb', '0016_auto_20210725_1643'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dodatkoweinfo',
            name='gatunek',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Inne'), (2, 'Sci-fi'), (4, 'Drama'), (1, 'Horror'), (3, 'Komedia')], default=0),
        ),
        migrations.AlterField(
            model_name='ocena',
            name='autor',
            field=models.CharField(blank=True, default='Anonim', max_length=64, null=True),
        ),
    ]
