# Generated by Django 3.2.4 on 2021-07-25 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filmweb', '0017_auto_20210725_1650'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dodatkoweinfo',
            name='gatunek',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Inne'), (1, 'Horror'), (2, 'Sci-fi'), (4, 'Drama'), (3, 'Komedia')], default=0),
        ),
    ]
