# Generated by Django 3.2.4 on 2021-07-25 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filmweb', '0019_auto_20210725_1655'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ocena',
            name='autor',
        ),
        migrations.AlterField(
            model_name='dodatkoweinfo',
            name='gatunek',
            field=models.PositiveSmallIntegerField(choices=[(3, 'Komedia'), (4, 'Drama'), (2, 'Sci-fi'), (0, 'Inne'), (1, 'Horror')], default=0),
        ),
    ]
