# Generated by Django 3.2.4 on 2021-07-25 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filmweb', '0020_auto_20210725_1658'),
    ]

    operations = [
        migrations.AddField(
            model_name='ocena',
            name='autor',
            field=models.CharField(default='', max_length=64),
        ),
        migrations.AlterField(
            model_name='dodatkoweinfo',
            name='gatunek',
            field=models.PositiveSmallIntegerField(choices=[(2, 'Sci-fi'), (1, 'Horror'), (4, 'Drama'), (0, 'Inne'), (3, 'Komedia')], default=0),
        ),
    ]
