# Generated by Django 3.2.4 on 2021-07-25 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filmweb', '0021_auto_20210725_1702'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dodatkoweinfo',
            name='gatunek',
            field=models.PositiveSmallIntegerField(choices=[(4, 'Drama'), (0, 'Inne'), (2, 'Sci-fi'), (3, 'Komedia'), (1, 'Horror')], default=0),
        ),
        migrations.AlterField(
            model_name='ocena',
            name='autor',
            field=models.CharField(default='', editable=False, max_length=64),
        ),
    ]
