# Generated by Django 3.2.4 on 2021-07-25 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filmweb', '0022_auto_20210725_1706'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dodatkoweinfo',
            name='gatunek',
            field=models.PositiveSmallIntegerField(choices=[(3, 'Komedia'), (1, 'Horror'), (0, 'Inne'), (4, 'Drama'), (2, 'Sci-fi')], default=0),
        ),
        migrations.AlterField(
            model_name='ocena',
            name='autor',
            field=models.CharField(blank=True, default='', editable=False, max_length=64, null=True),
        ),
    ]
