# Generated by Django 3.2.4 on 2021-07-25 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filmweb', '0023_auto_20210725_1711'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dodatkoweinfo',
            name='gatunek',
            field=models.PositiveSmallIntegerField(choices=[(3, 'Komedia'), (0, 'Inne'), (2, 'Sci-fi'), (1, 'Horror'), (4, 'Drama')], default=0),
        ),
        migrations.AlterField(
            model_name='ocena',
            name='autor',
            field=models.CharField(blank=True, default='anonim', max_length=64, null=True),
        ),
    ]
