# Generated by Django 3.2.4 on 2021-07-26 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filmweb', '0025_auto_20210725_1719'),
    ]

    operations = [
        migrations.AddField(
            model_name='ocena',
            name='autor',
            field=models.CharField(blank=True, default='Anonim', max_length=64),
        ),
        migrations.AlterField(
            model_name='dodatkoweinfo',
            name='gatunek',
            field=models.PositiveSmallIntegerField(choices=[(2, 'Sci-fi'), (1, 'Horror'), (4, 'Drama'), (3, 'Komedia'), (0, 'Inne')], default=0),
        ),
    ]
