# Generated by Django 3.2.4 on 2021-07-26 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filmweb', '0027_alter_dodatkoweinfo_gatunek'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dodatkoweinfo',
            name='gatunek',
            field=models.PositiveSmallIntegerField(choices=[(2, 'Sci-fi'), (3, 'Komedia'), (0, 'Inne'), (4, 'Drama'), (1, 'Horror')], default=0),
        ),
        migrations.AlterField(
            model_name='ocena',
            name='autor',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
    ]
