# Generated by Django 3.2.4 on 2021-07-26 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filmweb', '0028_auto_20210726_1108'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ocena',
            old_name='autor',
            new_name='autor56',
        ),
        migrations.AlterField(
            model_name='dodatkoweinfo',
            name='gatunek',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Inne'), (3, 'Komedia'), (2, 'Sci-fi'), (1, 'Horror'), (4, 'Drama')], default=0),
        ),
    ]
