# Generated by Django 3.2.4 on 2021-07-26 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filmweb', '0029_auto_20210726_1116'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ocena',
            old_name='autor56',
            new_name='autor',
        ),
        migrations.AlterField(
            model_name='dodatkoweinfo',
            name='gatunek',
            field=models.PositiveSmallIntegerField(choices=[(2, 'Sci-fi'), (3, 'Komedia'), (4, 'Drama'), (0, 'Inne'), (1, 'Horror')], default=0),
        ),
    ]
