# Generated by Django 3.2.4 on 2021-07-26 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filmweb', '0030_auto_20210726_1119'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dodatkoweinfo',
            name='gatunek',
            field=models.PositiveSmallIntegerField(choices=[(2, 'Sci-fi'), (0, 'Inne'), (4, 'Drama'), (1, 'Horror'), (3, 'Komedia')], default=0),
        ),
        migrations.AlterField(
            model_name='ocena',
            name='autor',
            field=models.CharField(default='', max_length=64),
        ),
    ]
