# Generated by Django 3.2.4 on 2021-07-26 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filmweb', '0031_auto_20210726_1124'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dodatkoweinfo',
            name='gatunek',
            field=models.PositiveSmallIntegerField(choices=[(4, 'Drama'), (2, 'Sci-fi'), (3, 'Komedia'), (1, 'Horror'), (0, 'Inne')], default=0),
        ),
        migrations.AlterField(
            model_name='ocena',
            name='autor',
            field=models.CharField(default=1, max_length=64),
        ),
    ]
