# Generated by Django 3.2.4 on 2021-07-26 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filmweb', '0032_auto_20210726_1125'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ocena',
            name='autor',
        ),
        migrations.AlterField(
            model_name='dodatkoweinfo',
            name='gatunek',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Horror'), (2, 'Sci-fi'), (4, 'Drama'), (0, 'Inne'), (3, 'Komedia')], default=0),
        ),
    ]
