# Generated by Django 3.2.4 on 2021-07-26 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filmweb', '0033_auto_20210726_1126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dodatkoweinfo',
            name='gatunek',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Inne'), (4, 'Drama'), (1, 'Horror'), (3, 'Komedia'), (2, 'Sci-fi')], default=0),
        ),
        migrations.AlterField(
            model_name='ocena',
            name='gwiazdki',
            field=models.PositiveSmallIntegerField(default=5, max_length=5),
        ),
    ]
