# Generated by Django 3.2.4 on 2021-07-26 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filmweb', '0035_auto_20210726_1308'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dodatkoweinfo',
            name='gatunek',
            field=models.PositiveSmallIntegerField(choices=[(3, 'Komedia'), (2, 'Sci-fi'), (0, 'Inne'), (1, 'Horror'), (4, 'Drama')], default=0),
        ),
        migrations.AlterField(
            model_name='ocena',
            name='gwiazdki',
            field=models.PositiveSmallIntegerField(default=5),
        ),
    ]
